import type { ThemeManifest, ThemeConfigValues } from "@/core/theme";

export const manifest: ThemeManifest = {
  name: "zoomg",
  version: "1.0.0",
  author: "maddyBlog",
  description: "Zoomg — a professional Persian gaming & entertainment magazine theme inspired by zoomg.ir, with RTL support, dark mode, and fully customizable sections.",
  previewImage: "/themes/zoomg/preview.png",
  supportedFeatures: [
    "stories",
    "featured-slider",
    "category-sections",
    "author-card",
    "related-posts",
    "sidebar",
    "newsletter",
    "search",
    "categories",
    "tags",
    "reading-time",
    "dark-mode",
    "social-share",
  ],
  configurationSchema: {
    fields: [
      {
        key: "accent",
        label: "Accent Color",
        type: "color",
        defaultValue: "#EE2D58",
        description: "Main accent color (primary pinkish-red like zoomg.ir)",
      },
      {
        key: "accentLight",
        label: "Accent Light",
        type: "color",
        defaultValue: "#FFF0F3",
        description: "Light accent background tint",
      },
      {
        key: "accentDark",
        label: "Accent Dark",
        type: "color",
        defaultValue: "#EA3244",
        description: "Darker accent shade for hover states",
      },
      {
        key: "bgPrimary",
        label: "Background Primary",
        type: "color",
        defaultValue: "#F9F9F9",
        description: "Main page background color",
      },
      {
        key: "bgSecondary",
        label: "Background Secondary",
        type: "color",
        defaultValue: "#FFFFFF",
        description: "Card and section background color",
      },
      {
        key: "textPrimary",
        label: "Text Primary",
        type: "color",
        defaultValue: "#32323C",
        description: "Main text color",
      },
      {
        key: "textMuted",
        label: "Text Muted",
        type: "color",
        defaultValue: "#767676",
        description: "Secondary/muted text color",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "color",
        defaultValue: "#E9E9E9",
        description: "Border and divider color",
      },
      {
        key: "cardBg",
        label: "Card Background",
        type: "color",
        defaultValue: "#FFFFFF",
        description: "Card background color",
      },
      {
        key: "fontFamily",
        label: "Font Family",
        type: "font",
        defaultValue: "IRANSansX",
        options: [
          { label: "IRANSansX (Persian)", value: "IRANSansX" },
          { label: "Vazirmatn", value: "Vazirmatn" },
          { label: "Inter", value: "Inter" },
          { label: "System UI", value: "system-ui" },
        ],
      },
      {
        key: "layout",
        label: "Layout Style",
        type: "select",
        defaultValue: "magazine",
        options: [
          { label: "Magazine", value: "magazine" },
          { label: "Compact", value: "compact" },
          { label: "Grid", value: "grid" },
          { label: "List", value: "list" },
        ],
      },
      {
        key: "containerWidth",
        label: "Container Width",
        type: "number",
        defaultValue: 1320,
        description: "Maximum content width in pixels",
      },
      {
        key: "showStories",
        label: "Show Stories Bar",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showFeaturedSlider",
        label: "Show Featured Slider",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showAuthorBox",
        label: "Show Author Box",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showReadingTime",
        label: "Show Reading Time",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showRelatedPosts",
        label: "Show Related Posts",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showSidebar",
        label: "Show Sidebar",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showTrending",
        label: "Show Trending Section",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "showNewsletter",
        label: "Show Newsletter Signup",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "maxPostsPerPage",
        label: "Posts Per Page",
        type: "number",
        defaultValue: 12,
        description: "Number of posts to show on the homepage",
      },
      {
        key: "gridColumns",
        label: "Grid Columns",
        type: "select",
        defaultValue: "3",
        options: [
          { label: "2 Columns", value: "2" },
          { label: "3 Columns", value: "3" },
          { label: "4 Columns", value: "4" },
        ],
      },
    ],
    groups: [
      {
        label: "Colors",
        key: "colors",
        fields: [
          "accent", "accentLight", "accentDark",
          "bgPrimary", "bgSecondary",
          "textPrimary", "textMuted",
          "borderColor", "cardBg",
        ],
      },
      {
        label: "Typography & Layout",
        key: "layout",
        fields: ["fontFamily", "layout", "containerWidth", "gridColumns"],
      },
      {
        label: "Sections",
        key: "sections",
        fields: ["showStories", "showFeaturedSlider", "showTrending", "showSidebar", "showNewsletter"],
      },
      {
        label: "Content",
        key: "content",
        fields: ["showAuthorBox", "showReadingTime", "showRelatedPosts", "maxPostsPerPage"],
      },
    ],
  },
};

export const defaultConfig: ThemeConfigValues = {
  accent: "#EE2D58",
  accentLight: "#FFF0F3",
  accentDark: "#EA3244",
  bgPrimary: "#F9F9F9",
  bgSecondary: "#FFFFFF",
  textPrimary: "#32323C",
  textMuted: "#767676",
  borderColor: "#E9E9E9",
  cardBg: "#FFFFFF",
  fontFamily: "IRANSansX",
  layout: "magazine",
  containerWidth: 1320,
  gridColumns: "3",
  showStories: true,
  showFeaturedSlider: true,
  showAuthorBox: true,
  showReadingTime: true,
  showRelatedPosts: true,
  showSidebar: true,
  showTrending: true,
  showNewsletter: true,
  maxPostsPerPage: 12,
};
